/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ia.nim;

import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author GCM-Ataks
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUno = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JButton();
        txtVwMov = new javax.swing.JLabel();
        txtVwTurno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnUno.setText("Pz. Uno");
        getContentPane().add(btnUno);
        btnUno.setBounds(10, 11, 83, 23);

        btnDos.setText("Pz. Dos");
        getContentPane().add(btnDos);
        btnDos.setBounds(10, 44, 83, 23);

        btnTres.setText("Pz. Tres");
        getContentPane().add(btnTres);
        btnTres.setBounds(10, 73, 83, 23);

        btnCuatro.setText("Pz. Cuatro");
        getContentPane().add(btnCuatro);
        btnCuatro.setBounds(10, 102, 83, 23);

        btnCinco.setText("Pz. Cinco");
        getContentPane().add(btnCinco);
        btnCinco.setBounds(10, 131, 83, 23);

        btnSeis.setText("Pz. Seis");
        getContentPane().add(btnSeis);
        btnSeis.setBounds(10, 160, 83, 23);

        btnSiete.setText("Pz. Siete");
        getContentPane().add(btnSiete);
        btnSiete.setBounds(10, 189, 83, 23);

        jLabel2.setText("Movimientos Restantes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 200, 111, 14);

        jLabel3.setText("Turno:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 20, 32, 14);

        btnTerminar.setText("TERMINAR TURNO");
        getContentPane().add(btnTerminar);
        btnTerminar.setBounds(150, 70, 155, 110);

        txtVwMov.setText("0");
        getContentPane().add(txtVwMov);
        txtVwMov.setBounds(280, 220, 6, 14);

        txtVwTurno.setEditable(false);
        txtVwTurno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVwTurno.setText("Humano");
        getContentPane().add(txtVwTurno);
        txtVwTurno.setBounds(190, 30, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtVwMov;
    private javax.swing.JTextField txtVwTurno;
    // End of variables declaration//GEN-END:variables
}
